server:
  port: 7035
spring:
  application:
    name: @pom.artifactId@
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    url: jdbc:mysql:///pili_base_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 100000MB
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
    mongodb:
      uri: mongodb://localhost:27017/pilipili
web:
  upload-path:
    D:/pilipili_data/temp/
  static-path:
    images:
      # 视频封面路径
      video_cover: /images/video_cover/
      # 用户头像地址
      user_avatar: /images/user/avatar/
    media:
      video: /media/video/
security:
  oauth2:
    resource:
      id: @pom.artifactId@
      user-info-uri: http://localhost:8004/api/uaa/currentUser
      prefer-token-info: false
