server:
  port: 7035
spring:
  application:
    name: @pom.artifactId@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql:///pili_base_db?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
web:
  upload-path:
    D:/pilipili_data/temp/
  static-path:
    images:
      # 视频封面路径
      video_cover: /images/video_cover/
      # 用户头像地址
      user_avatar: /images/user/avatar/