server:
  port: 8004
  tomcat:
    remote-ip-header: x-forward-for
    uri-encoding: UTF-8
    max-threads: 10
    basedir: /deployer/tomcat
spring:
  application:
    name: @pom.artifactId@
  servlet:
    multipart:
      max-file-size: 2048MB
      max-request-size: 100000MB
zuul:
  routes:
    uac:
      path: /api/uac/**
      sensitiveHeaders:
      serviceId: pili-provider-uac
    uaa:
      path: /api/uaa/**
      sensitiveHeaders:
      serviceId: pili-security
    mdc:
      path: /api/mdc/**
      sensitiveHeaders:
      serviceId: pili-provider-mdc
ribbon:
  ReadTimeout: -1
  ConnectTimeout: 10000


